# PhD work

This is a summary of all the work that I have done in my PhD until now. 
(mainly it's about software implementations related to the core technologies 
within the group). **To include in the thesis text**.

Note though that not all of these will be part of the main thesis (maybe include the 
rest in a section like 'Funny PhD side-quests').

## Druglogics Pipeline {-}

- Lots of refactoring to increase the readability, maintainability and 
extendability of the source code (complete restructure of classes, addition of
others). 
This has **RRI extensions**, because cleaning and re-structuring software code has a social aspect to it in the sense that other people can now contribute more easily, extend the code, use it (user perspective can bring changes and further improvements to software pipeline even though they may be used for research purposes) - how can you expect users to actually use a piece of code when it's not substantially documented and it's internal logics made obscure because nobody gave attention to detail and structure? How can anybody care for a (software and any) product that you have not cared enough so as to present it in an way that is acceptable, managable and proper?
- Bug fixing
- Enable maven packaging for easier source compilation, testing, 
installation, management and executing of the code
- Added tests to modules `gitsbe` and `drabme` using [JUnit5](https://junit.org/junit5/), [mockito](https://site.mockito.org/) and [assertJ](https://assertj.github.io/doc/) libraries
- [Source code documentation](https://druglogics.github.io/druglogics-doc/) with bookdown for Drabme and Gitsbe
- Enabling *parallel simulations* in Gitsbe (performance optimization)
- Added support for many features (see [dev_plan_doc](http://tiny.cc/DLDevPlan))
- [Druglogics ROC generator](https://github.com/bblodfon/druglogics-roc):
R shiny app to assess the performance of the Drabme results in the form of a 
ROC curve
- Export support using [BioLQM](https://github.com/colomoto/bioLQM): the initial model + best generation models can now be exported through configuration options to **GINML, SBML-Qual and BoolNet** community formats
- **Attractor calculation** (stable states and minimal trapspaces) using [BioLQM](https://github.com/colomoto/bioLQM)
- [abmlog](https://github.com/druglogics/abmlog) package.
- `emba` [@R-emba].
  See [gitsbe-model-analysis repository](https://github.com/bblodfon/gitsbe-model-analysis/) with various analysis using this package (input is files from `gitsbe`).

### Attractor Tools performance comparison {-#attrToolCmp}

Some preliminary results comparing **fixpoint** and **trapspace** calculation tools using the following 2 topologies: **CASCADE 1.0** (77 nodes and 149 edges) and **CASCADE 2.0** (144 nodes, 367 edges). Both of these models are self-contained (no inputs, less attractors). 

Tools tested (**fixpoints**): `BNReduction` (full and reduced version - the second is considerably faster (main reason we were using it), but does not find more than 1 stable state which was more like a feature we wanted especially for larger self-contained networks), `BioLQM (BDD-based)`.

Tools tested (**trapspaces**): `BioLQM (BDD-based)` vs `PyBoolNet` (I also tried the ASP-based solver of BioLQM but it was slower than the BDD-based algorithm, as Aurelien states in the [documentation](http://colomoto.org/biolqm/doc/tools-trapspace.html))

- FIXPOINTS
  - CASCADE 1.0: BioLQM(fixpoints) << BNReduction(reduced) (~same time to calculate the trapspaces using BioLQM!) << BNReduction(full).
  - CASCADE 2.0: BNReduction(reduced) << BNReduction(full) < BioLQM(fixpoints)

So, for our smaller topology, we can actually use the BioLQM stable state calculation and it will give us complete fixpoint results even faster than the BNReduction (reduced version) we are using currently. Even more: **we could use the BioLQM trapspace computation for that smaller model! For the larger network though, I am afraid BioLQM does not scale as well as the BNReduction does.**

- TRAPSPACES
  - PyBoolNet << BioLQM, no matter the model chosen. Especially for the larger network, BioLQM takes several minutes when PyBoolNet takes less than 10 seconds. For the smaller topology, it's the same difference in scale but in millisecs (PyBoolNet: ~10msecs, BioLQM: ~200msecs per model).
  - MPBN(https://github.com/pauleve/mpbn/) >> PyBoolNet. 
  The sad thing is the overhead you get when runnng the Python module through java which is actually longer for smaller networks than the calculation of the trapspaces themselves! Implemented in the pipeline now.

## VSM {-}

I made `vsm-dictionaries` with a focus on the biological domain.
We call them UBDs: *Unified Biological Dictionaries*.
See [UBD GitHub organisation page](https://github.com/UniBioDicts).

Most of this work is done in order to support Vasundra's [causalBuilder Tool](https://mi2cast.github.io/causalBuilder/) which is the first application of VSM after SciCura v1.

## PSICQUIC {-}

My work at the EBI with IntAct and Noemi Del Toro to extend the PSICQUIC web service to support the
MITAB 2.8 data format. 
See the [psicquic doc](http://psicquic.github.io/MITAB28Format.html) and the casualTab paper [@Perfetto2019].

I also worked with Noemi on the update of the [JAMI](https://github.com/MICommunity/psi-jami) 
library to also support MITAB 2.8 - this is the culmination of results from the 
[BioHackathon 2018, in Paris](https://2018.biohackathon-europe.org/) and the 
[Marseille GREEKC hackathon event](https://github.com/GREEKC/hackathon-marseille/tree/master/project_descriptions/causal_psicquic).

## Others {-}

- Java Client for RSAT tool [fetch-sequences](https://github.com/bblodfon/rsat-rest-java-clients)
- `usefun` [@R-usefun] (for the community!)
- `rtemps` [@R-rtemps] (for the community!)
