# PhD Papers

Note that the titles and the details for each paper are liable to change though the core ideas behind should not. 

### Paper I: `emba` - an R package for ensemble boolean model biomarker analysis {-}

#### Authors {-}

John, Asmund

#### Idea {-}

This whole thing started when we questioned the predictive performance of the models generated by `Gitsbe`:

- What kind of insights can we get from such a dataset by looking at each individual model's boolean equations, stable states and predictive performance? 
- How can we take back such knowledge and use it in order to understand more about how to generate better models in our pipeline?
- How can we analyse each model's data to find nodes whose activity state or boolean model parameterization affects the manifestation of specific observed synergies? 

These questions and more of the same kind lead to a large data exploration and analyses, me writing a lot of `R` code, which I ended up splitting to two packages: [@R-usefun] and [@R-emba].

The idea behind the `emba` R package is to have simple functions that will help us analyse the models produced by `Gitsbe` in order to find important nodes (biomarkers) responsible for either better performance (based on a metric score like MCC) or for specific synergy(ies) prediction. 

#### What might come of this? {-}

- The R package emba [@R-emba] is publishable by itself as an **application note paper**, but we decided with Asmund that is best to present it with an analysis on some dataset to show its use. 
For example, the package is used for analyses that will be included in Asmund's paper(s), e.g. *AGS Story: Part I* among others.

- Another idea is to compare Machine Learning results with my method (on cascade/atopo results of the pipeline paper or other). 
Paper could be titled something along the lines of **"Ensemble model analysis vs Machine Learning for unraveling drug synergy mechanisms"**.

- Another idea here is the results of the project **Optimize the predictive performance of the Druglogics pipeline**. 
One of the research questions here is about the **identification of optimal training data size and included nodes which are essential for good performance** (with Eirini, I am leading it).

### Paper II: *UniBioDicts*: Unified access to biological dictionaries {-}

#### Authors {-}

John, Vasundra, Martin, Steven

#### Idea/Implementation {-}

A short **application note** paper for my work on the [UniBioDicts](#vsm).
