# PhD Tasks and Plans {#plans}

## Programming Tasks TODO

Tasks that I have promised that I will do to different people within the group. 
These tasks enable other workflows/collaborations, etc. so they are very 
important to finish before I move on to other work. You see only what's left of 
those:

- Pipeline (see the [dev_plan_doc](https://docs.google.com/document/d/1OUupR0b-28YB9pVAww77RMecnFN6A39MYjXMjljmvG4/edit?usp=sharing) for what is left). Most important:
    - Full BioLQM support: stable state calculation and trap spaces
    - Do comparison between Aurelien's BioLQM stable state algorithm and 
BNReduction using M2 or without (Asmund already says that it BNReductions is faster
but it's good to prove it once again)
- VSM
  - Make the `vsm-pub-dictionaries` module

## Papers

Note that the titles and the details for each paper are liable to change though the core ideas behind should not. 

The papers dictate my future work for this PhD (and in that order!).

### Paper I: *emba*: an R package for ensemble boolean model biomarker analysis {-}

#### Authors {-}

John, Asmund

#### Idea {-}

The idea here is to analyse the models produced by `Gitsbe` in order to find important nodes (biomarkers) responsible for either better performance (based on a metric score like TP or MCC) or for specific synergy(ies) prediction. 

The R package emba [@R-emba] is publishable by itself as an **application note paper**,
but we decided with Asmund that is best to present with an analysis on some dataset
to show it's use. The package is also used for analyses that will be included in 
Asmund's automated pipeline paper (on the cascade topology mostly).

An idea is to compare ML results with my method (on cascade/atopo results of the pipeline 
paper or other). Paper could be titled something along the lines of
**"Ensemble model analysis vs Machine Learning for unraveling drug synergy mechanisms"**.
(which depends only on me). Could also be that I combine Vasundra's and 
Barbara's computational work on the biomarker analysis with mine and the ML 
methods (so more generic even) to create a nice combo paper about **"Unraveling drug mechanisms on CRC 
cell lines using various computational methods"**. 

A research question here (with similar kind of work) is about the 
**identification of optimal training data size**, in the sense that we can use 
various methods to derive a node (biomarker) set for the training data (with Eirini).

### Paper II: *VSM-dictionaries*: common access to biological dictionaries {-}

#### Authors {-}

John, Steven, Vasundra, Martin

#### Idea/Implementation {-}

A short **application note** paper for my work on [VSM-dictionaries](#vsm-dict).

### Paper III: From causal statements to building logical models compliant with biological knowledge {-}

#### Authors {-}

John, others (to decide)

#### Idea {-}

This paper will be the main **research paper of my PhD**.
This idea is like a continuation of the `causalBuilder` tool by Vasundra coupled with the
need to have a more proper representation of complexes (and families) in our 
logical models (better models, better predictions). Asmund had *manually* changed some logical equations in his paper 
[@Flobak2015], in order to make the model more compliant with biology knowledge 
and literature findings. One of them was about the beta-catenin complex and its
constituents (connected with *AND's* instead of *OR's*) and the rest were about changing the link operators of the logical 
equations (from *AND NOT* to *OR NOT*). The latter is something that is enabled 
through the mutations introduced by the genetic algorithm of `Gitsbe`. The former
depends on the dataset and the representation of complexes ^[There is actually a mutation that can change this but not in the way that we want - i.e. all components of a complex 
should be connected with an *AND*]. 

Only Signor has some complexes + interaction data but they are seperate files, making it thus difficult (and non-elegant computationally-wise) to integrate such knowledge/data to boolean models. Also Vasundra's experience with Reactome data in miTab2.8 showed us the difficulty to match binary interactions to a data model flexible enough to represent complexes and their internal components. Causal-JSON and the recursive schema that we thought allows the curator to put both the complex ID and it's constituents in the same data structure. And what's best than using a proper tool to annotate such causal statements like VSM!

#### Proposed Workflow {-}

So, the general semi-automated web-application (web only if VSM comes into play) pipeline for this paper that I am thinking will be as follows ^[My goal here is to combine as much as possible different things within our group,
so each point or package should be small, their combination effect large]:

1. Get interaction + complexes/families data (Signor most probably or a form of Cascade + complexes???). Note that for the reason I explained above miTab 2.8 is out of the question, so the Signor
data I am refering to is the .tsv files they offer (interaction data, complexes, families). And
most probably I am referring to a **pathway interaction dataset** not the whole Signor data. For example, the [Wnt Signaling pathway](https://signor.uniroma2.it/pathway_browser.php?organism=human&pathway_list=SIGNOR-WNT&level=1).
2. Build a small module that translates the (Signor) data to Causal-JSON. 
3. Optionally ^[might actually take a lot more effort than what I am planning that's why it's optional] 
there can be support for (re-)curation of the data with VSM template(s) for proper annotation of complexes (the templates will be automatically pre-filled to match Signor's data model). Note that this implies causal-JSON => VSM-box JSON format, which is the reverse 
of what causalBuilder will do. It will be nice if such interface supports addition
of one more template of the same thing to curate one new sentence and add it to the data. 
The thing is that I want to include VSM into this, but I don't yet know how to really support
its place in this pipeline since the curation is already done from Signor. It can be
part of a showcase though: an example causal statement from the pathway with a complex 
and how it could be cureated with VSM.
3. **Main:** Build a package that translates the causal-JSON data to a logical model with
some filtering and parameterization included (e.g. filter based on cell line (so *cell-line* specific topologies), conditions on the biological state: 'by phoshorylation', exp. evidence, assertion/confidence score, species, compartment). 
So, **causal-JSON to .bnet files (logical equations)**, while substituting nicely ^[huge
discussion here, but I already know what to do pretty much] the complexes and families. 
4. Showcase some small application of this logical model end-product:  
    - use for example the [colomoto notebook](https://github.com/colomoto/colomoto-docker), do some small trapspace analysis and show that some results from literature or from previous logical or other models can now be reproduced with a better biological representation in the model itself
    - make many logical models of the pathways in Signor with simple attractor analysis and put them into the GinSim model repository for reference for the logical community.
    - extend `atopo` module to use the main (3) package and use it for finding drug combinations (comparing attractors or prediction results of automated topology building without complexes vs automated topology built from causal-JSON with complexes and families in each case). 
    The main thing here would be of course better prediction performance results based on a better logical model representation. 
    I could tweak `atopo` to choose actually not all of Signor's data but specific pathways to include in the analysis and this will help I believe to build smaller topologies for specific drug combinations that we want to test.

Interesting resources:

- Signor Pathway data
- CausalBuilder
- [CancerGeneNet](https://doi.org/10.1093/nar/gkz871)

## Other Paper Ideas

### Paper IV (Deprecated) {-}

#### Title {-}

Extending `SynergyFinder` for the use of multiple reference models for the assement of synergy in screening datasets

#### Idea {-}

The core idea here is to extend an existing R package for calculating synergy 
reference models in order to include Wim's generalized Bliss method and the mean synergy score by Simone Laderer! Then I will test all the null reference models (Loewe, Bliss, ZIP, +2 new, others?) on dose-response matrix datasets (could be from Ladere's paper, from Asmund's paper, our own - Barbara's/Evelina's dataset, etc.) and see which is best at finding the synergies in each dataset.

R package to use:

- SynergyFinder from Finland group [code here](https://github.com/google/synergyfinderengineered/)
- Also I have to check this software: [R package COMBIA](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5732778/) as well as others at the time I will be tackling this

Also, I should investigate if my own idea for a mathematical 
formulation of the volume-based synergy score as general method for describing 3-wise 
or more combinations as synergistic, could be part of this implementation (or could be another paper by itself).

### Paper V (Why not?!) {-}

#### Authors {-}

John, others (to decide)

#### Title {-}

On eye-balling synergy mechanisms: What is a ~~mountain~~ synergy?

#### Idea {-}

I had the idea of writing a small paper (send to Science Signaling) that describes the *eye-ball* or 
*visual inspection* technique that is used so much in computational Biology and 
Medicine. It is used pretty much in any paper I have seen but nobody has actually
defined or named it.

A characteristic example is the *call for synergy* when you see some 
experimental data in dose-response curves (show mostly when you see figures). Another is the threshold that data analysts put when defining output to classifiers or the parameterization that is used and the general human intuition/engineering that is shared in all these.

As Asmund once said:

> What is a mountain? What is a synergy?

So, I just want to discuss this in a small paper cause it seems to be a
thing that everybody is aware of in their everyday job, but everyone keeps out 
when talking about results, etc and I haven't found a paper that discusses this
one way or another!
A very RRI-related paper...

