# (APPENDIX) Appendix {-}

# Links to software, documentation and data analyses {-}

\vspace{-10pt}

## GitHub organizations {-#github-org-links}

- UniBioDicts: https://github.com/UniBioDicts/ 
- VSM: https://github.com/vsm
- DrugLogics: https://github.com/druglogics
- PSICQUIC: https://github.com/PSICQUIC

## Documentation {-#doc-links}

- DrugLogics software: https://druglogics.github.io/druglogics-doc/
- VSM technology and related projects: https://vsm.github.io/
- PSICQUIC: https://psicquic.github.io/

## DrugLogics software modules {-#druglogics-soft-links}

- [`gitsbe`](https://github.com/druglogics/gitsbe): A Java module that defines Boolean models compliant with observed behavior (e.g. steady state or perturbation data) using an automated, model parameterization genetic algorithm
- [`drabme`](https://github.com/druglogics/drabme): A Java module that performs a drug perturbation response analysis to the Boolean model ensembles generated by gitsbe
- [`druglogics-synergy`](https://github.com/druglogics/druglogics-synergy): A Java module to execute serially gitsbe and then drabme
- [`abmlog`](https://github.com/druglogics/abmlog): A Java-based generator of all possible logical models with AND/OR-NOT link operators in their respective Boolean equations
- [`druglogics-roc`](https://github.com/druglogics/druglogics-roc): `R` Shiny web app to visualize the ROC and PR prediction performance of drabme's ensemble-wise predictions
- [`emba`](https://github.com/bblodfon/emba/): `R` package for analysis and visualization of biomarkers in Boolean model ensembles

## R community packages {-}

- [`usefun`](https://github.com/bblodfon/usefun): various useful `R` functions
- [`rtemps`](https://github.com/bblodfon/rtemps): templates for reproducible data analyses with `R` [@rtemps]

## Miscellaneous data analyses and repositories {-#misc-links}

All the following repositories have been authored exclusively by myself.
Each repository has a `README.md` file with a brief description of the analysis and a link to online documentation and results (in the form of `R` Markdown documents or `R` GitBooks).

- [`CASCADE`](https://github.com/druglogics/cascade): repository of the CAncer Signaling CAusality DatabasE developed by the DrugLogics group and its subsequent versions
- [`ags-paper`](https://github.com/druglogics/ags-paper): simulation results and data analyses related to the AGS paper manuscript
- [`sintef-obs-synergies`](https://github.com/druglogics/sintef-obs-synergies): synergy assessment of the Flobak et al. (2019) @Flobak2019 drug combination dataset using rbbt [@Vazquez2010] and the CImbinator tool [@Flobak2017]
- [`brf-bias`](https://github.com/druglogics/brf-bias): data analyses related to truth density bias in standardized Boolean regulatory functions (results are part of the Boolean function metrics paper)
- [`gitsbe-model-analysis`](https://github.com/druglogics/gitsbe-model-analysis): several analyses using Boolean model ensemble datasets generated via gitsbe and the emba `R` package to analyze them
- [`bool-param-maps`](https://github.com/druglogics/bool-param-maps): visualization of model parameterization and node importance using UMAP and random forests on the CASCADE 1.0 Boolean model dataset generated by `abmlog`
