## Acknowledgements {-}

I would like to **thank all the people** that interacted with me during the years I conducted my PhD (2017-2021), even for a tiny bit.
A person is only a small part of a complex network of interactions and all of them taken together (small or large), constitute the person.
So you were **all important**!

Now, for the personal credits you all came here to read:

A big **THANK YOU** to my supervisor, Prof. Martin Kuiper.
He gave me the opportunity to come to Norway, which opened a world of possibilities.
The dream supervisor everyone should have and a caring human being above all.

To Dr. Asmund Flobak for excellent co-supervision, the nice scientific discussions we had and for introducing me into `R`, which largely influenced the way I do science.
Spending time with his family was also a new thing for me, kids can have so much energy and drain yours, a good thing to know about!

To Dr. Steven Vercruysse for our discussions, during which he helped me progress professionally.
Apart from our common passion for coding, we had some good laughs too - I will never forget the ELIXIR Biohackathon 2020, good times right there.

To Noemi Del Toro Ayllon, for introducing me to the professional world of software development and project management with Java.
Visiting the IntAct team at EBI during the summer of 2018 was a blast and when she came in Trondheim we had such a good time, so thank you Noe!

To Prof. Astrid Laergid, for suggesting to me to participate in the Responsible Research and Innovation (RRI) course, which allowed me to think more broadly about my research and the world we live in, and of course meet several wonderful people!
As a direct consequence, I had the opportunity to be part of a Walkshop in Jutenheimen (September 2019), which was an amazing experience - truly wonderful pre-corona times.

And special thanks to Liv Falkenberg, for being an excellent coordinator of the Digital Life Norway Research School initiative, allowing me to participate in various conferences across Norway and for the opportunity to do an industry internship in Sweden during the cold winter of 2021.

To my colleagues from the DrugLogics group, for the good times we spent inside and outside of work!
I am grateful to Dr. Barbara Niedertofter for our piano-voice collab.
Rafel Reiduvartes has been a really close friend - let's hope that we will continue our long random walks that accidentally end up in McDonalds.
Marcio Luis Acencio has been a good friend as well with a wonderful family that gained new members that I got to play with before he left the group!
Dr. Vasundra Toure has been a *standard*, close friend, wonderful colleague.
Wine, cheese and standards!

To Henning Hermjacob, not for just being the scientific lead host for my visits to EBI, but also for hosting me in his lovely Airbnb house each time!
Being in Cambridge, England during my PhD, was a real nice change of pace, both professionally and .

To all cafes I've been and working throughout my PhD - I most certainly wouldn't be unable to complete the PhD without you!
As was perfectly stated:

[!]("img/less_depresson.png")

For Team Greece.
